spring.application.name=engagement-service
server.port=8083
spring.config.import=optional:configserver:

spring.datasource.url=jdbc:h2:mem:engagementdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
